mysql:
  host: ""
  port: 0
  database: ""
  table-prefix: "REDDITCRAFT"
  username: ""
  password: ""

auth:
  window-mins: 30
  confirmation-window-seconds: 30
  garbage-collector-cooldown-hours: 2

  verification:
    cooldown-seconds: 30
    reddit-message-subject: "REDDITCRAFT VERIFICATION"
    ambient-messages-expiry-days: 2
    # whether their flair on the subreddit is to be turned on after successfully having their reddit account verified.
    flair-on-after-success: false

subreddit:
  name: "YOUR SUBREDDIT"

  flairs:
    # prefixsync / singlegroups / multiplegroups
    mode: "prefixsync"

    # flair will be trimmed such that the combination is within the 64 char limit for flairs in prefixsync. in groups the groups will be reduced.
    format: "<flair> | <username>"

    # config for when a flair is set to off
    'off':
      # flair id of no flair
      id: ""
      # placeholders: <username> is minecraft username of player with flair off
      format: "[<username>]"

    # flair id for the "custom prefix" flairs
    custom-flairs-id: ""

    singlegroups-config:
      # for users that don't fit into any of the above groups
      default-flair-id: ""

      # the flair id for operators, since they satisfy every permission check
      op-flair-id: ""

      # highest priority comes at top, least at bottom
      flair-priorities: []
#        - "owner"
#        - "..."

      flairs: {}
#        owner:
#          id: ""
#          requires-permission: ""

    multiplegroups-config:
      # the flair id for operators, since they satisfy every permission check
      op-flair-id: ""

      delimiter: " | "

      flairs: {}
#        owner:
#          flair-text: "OWNER"
#          requires-permission: "group.owner"
#        zealous:
#          flair-text: "ZEALOUS"
#          requires-permission: "group.zealous"
#        bronze:
#          flair-text: "BRONZE"
#          requires-permission: "group.bronze"

      groups: {}
#        staff:
#          - "owner"
#        donor:
#          - "zealous"
#        standard:
#          - "bronze"

      group-priorities: []
#        - "staff"
#        - "donor"
#        - "standard"

placeholders:
  authenticatedredditusername:
    none: "NOT-AUTHENTICATED"
    error: "ERROR"

messages:
  prefix: "&8[&c&lReddit&f&lCraft&8] &f"

  general:
    error: "&cAn error occured executing this command. Please inform the developers."
    incorrect-usage: "&cIncorrect usage!"
    no-permission: "&cNo permission!"
    player-only-command: "&cThis command may only be executed by a player!"

  auth:
    verifier:
      success: "&aYour reddit account was successfully authenticated!"
      failure: "&cYour reddit account failed to authenticate. Please try again."
      success-but-flair-failed: "&aYour reddit account was successfully authenticated &c&lbut your flair on the subreddit failed to apply. &ePlease try to update it with &6/rc flair update&e, and if this fails contact the developers."
      error: "&cAn error occured when attempting to authenticate your reddit account. Please try again, and alert the developers if it persists."

    status:
      not-existing: "&cYou have never authenticated a reddit account."
      new: "&cYou do not have an authenticated reddit account. Previous unauthenticated reddit account username: &e<username>&a."
      new-failed: "&cYou have recently failed authenticating a reddit account with username &e<username>&c."
      in-progress: "&cYou have &e<time-left> minutes &cleft to authenticate your reddit account with username &e<username>&c."
      authenticated: "&aYou currently already have an authenticated reddit account with username &e<username>&a!"

      admin:
        not-existing: "&cThey have never authenticated a reddit account."
        new: "cThey do not have an authenticated reddit account. Previous unauthenticated reddit account username: &e<username>&a."
        new-failed: "&cThey have recently failed authenticating a reddit account with username &e<username>&c."
        in-progress: "&cThey have &e<time-left> minutes &cleft to authenticate their reddit account with username &e<username>&c."
        authenticated: "&aThey currently already have an authenticated reddit account with username &e<username>&a!"

  flair:
    not-authenticated: "&cYour reddit account is not authenticated! In order to access flairs, please authenticate your reddit account."

    status:
      'on': "&eYour flair is &aon&e. Your group and your username will show after updating your flair."
      'off': "&eYour flair is &coff&e. Only your username will show after updating your flair."
      'null': "&cYou have no flair. Please ensure you're authenticated."
      not-existing: "&cYou are not authenticated, and so have no flair. Please authenticate if you wish to show your username and/or group."

      admin:
        'on': "&eTheir flair is &aon&e. Their group and username will show after updating."
        'off': "&eTheir flair is &coff&e. Only their username will show after updating."
        'null': "&cThey have no flair."
        not-existing: "&cThey are not authenticated, and so have no flair. They must authenticate if they wish to show their username and/or group."

  commands:
    redditcraft:
      help:
        message: |-
          &eRedditCraft help:
           + &6auth &e- &7player authentication commands.&e
           + &6flair &e- &7player flair management commands.&e
           + &6admin &e- &7admin commands.
      authentication:
        help:
          message: |-
            &eAuthentication help:
             - &6begin <reddit username> &e- &7begin authenticating the given reddit username with your Minecraft account.&e
             - &6status &e- &7see your authentication status.&e
             - &6confirm &e- &7confirm an authentication procedure (you will only have to use this if prompted).
        begin:
          prompt: |
            &c&l» AUTHENTICATION PROCEDURE «

            &ePlease send a &cprivate message &eto the reddit account:
             » &6&l<bot-name>

            &ewith the following information:

             » &c&lSUBJECT&e: &6<subject>&e
             » &c&lBODY&e: &6<your Minecraft username>

            &efrom the reddit account:

             » &6&l<username>

            &eThen, within &c<window> seconds &eyour authentication message will be processed.
          confirm-prompt: '&aDo &e/rc auth confirm &awithin &e<confirm-window> seconds
            &ato confirm your change in reddit username...'
          invalid-args-amount: '&cPlease provide a single Reddit username.'
          invalid-username-format: '&cPlease enter a Reddit username of a valid format.'
          non-existing-username: '&cNo Reddit account found with the specified username!'
        confirm:
          invalid-args-amount: '&cThis command takes no arguments.'
          nothing-to-confirm: '&CNothing to confirm!'
          status-changed: '&cYour authentication status changed. &ePlease re-authenticate
            with &6/rc auth begin&e.'
          success: '&aAuthentication confirmation successful. Please proceed to verify
            your reddit account...'

      flair:
        help:
          message: |-
            &eFlair help:
             - &6on &e- &7turn on your flair on the subreddit. It will show both your group and your username after updating.&e
             - &6off &e- &7turn off your flair on the subreddit. It will show only your username after updating.&e
             - &6status &e- &7bbtain your local flair status.&e
             - &6update &e- &7update your flair on the subreddit to that described by your flair status.&e
             - &6remove &e- &7remove your flair from the subreddit. Neither your group nor your username will show. &cYou do not need to update to make this change.

        'on':
          success: |-
            &eFlair turned &aon&e! Your group and username will be visible.
             » Do &6/rc flair update &eto update it!
          error: "&cError turning on your flair. Please check your Reddit account is authenticated, otherwise inform the developers."

        'off':
          success: |-
            &eFlair turned &coff&e! Only your username will be visible.
             » Do &6/rc flair update &eto update it!
          error: "&cError turing off your flair. Please check your Reddit account is authenticated, otherwise inform the developers."

        update:
          success: "&eSuccessfully updated your flair to <status>&e!"
          error: "&cError updating your flair. Please check your Reddit account is authenticated, otherwise inform the developers."

        remove:
          success: "&eFlair &c&lremoved&e. You do not need to update it."
          error: "&cError removing your flair. Please check your Reddit account is authenticated, otherwise inform the developers."

      admin:
        help:
          message: |-
            &eAdmin help:
             + &6auth &e- &7admin authentication management commands.&e
             + &6flair &e- &7admin flair management commands.&e
             - &6reload &e- &7reload RedditCraft.&e
             - &6reset &e- &7reset the database data and reload the plugin &c(dangerous!)&e

        reload:
          begin-prompt: '&cReloading RedditCraft...'
          success-prompt: '&aRedditCraft reloaded!'

        authentication:
          help:
            message: |-
              &eAdmin authentication help:
               + &6verifier &e- &7admin verifier management commands.&e
               + &6garbage &e- &7database garbage collector admin commands.&e
               - &6force <minecraft uuid> <reddit username> &e- &7force-authenticate the reddit account with the given username to the minecraft account with the given uuid.&e
               - &6status <minecraft uuid> &e- &7obtain the authentication status of the minecraft player with the given uuid.&e
               - &6void <minecraft uuid> &e- &7void (unauthenticate if authenticated, cancel authentication attempt if in progress) a player's authentication status with the given uuid.&e
               - &6invalidatetokens &e- &7invalidate all in-progress authentication attempts &c(dangerous!)&e
               - &6resolve <reddit/minecraft> <reddit username/minecraft uuid> &8[all/*]&e - &7resolve the minecraft account authenticated with the given reddit username, or the reddit accounts authenticated with the given minecraft uuid. all/* additional parameter resolves all ASSOCIATED accounts, not just authenticated ones.
          garbagecollector:
            help:
              message: |-
                &eGarbage collector help:
                 - &6run &e- &7run the garbage collection procedure on the database.
          verification:
            help:
              message: |-
                &eVerification help:
                 - &6run &e- &7run the verifier verbosely (sends results to you).&e
                 - &6run quiet &e- &7run the verifier quietly (doesn't send the results to you).

        flair:
          help:
            message: |
              &eAdmin flair help:
               &7» NOTE: the main parameter to these commands is the UUID of the minecraft player you with to execute the command against.
               » if the &call &7or &c* &7parameter is available, it will apply the command to ALL AUTHENTICATED PLAYERS &c(dangerous!)&7
               » an additional "quiet" parameter causes the results to only be logged to console, and not sent to the sender.&e

               - &6on <minecraft uuid&c/all/*&6> &8[quiet] &e- &7attempt to turn on a minecraft player's flair.&e
               - &6off <minecraft uuid&c/all/*&6> &8[quiet] &e- &7attempt to turn off a minecraft player's flair.&e
               - &6remove <minecraft uuid&c/all/*&6> &8[quiet] &e- &7attempt to remove a minecraft player's flair. &c(do not need to update to make this go through!)&e
               - &6update <minecraft uuid&c/all/*&6> &8[quiet] &e- &7attempt to update a minecraft player's flair.&e
               - &6status <minecraft uuid> &e- &7attempt to obtain the status of a minecraft player's flair.&e








